import cozyDesk from "./assets/images/cozy-gaming-desk-setup-11.png";
import downtownOffice from "./assets/images/Downtown Office.jpeg";
import creativeLoft from "./assets/images/Creative Loft.jpg";
import techcoWork from "./assets/images/tech co-work.jpeg";

export const workspaces = [
  {
    id: 1,
    name: "Cozy Desk Hub",
    location: "Madhapur, Hyderabad",
    price: 200,
    image: cozyDesk,
    amenities: ["WiFi", "Coffee", "Printer", "Desk Lamp"],
  },
  {
    id: 2,
    name: "Downtown Office Suites",
    location: "Gachibowli, Hyderabad",
    price: 250,
    image: downtownOffice,
    amenities: ["WiFi", "Snacks", "Printer", "Lounge"],
  },
  {
    id: 3,
    name: "Creative Loft",
    location: "Banjara Hills, Hyderabad",
    price: 220,
    image: creativeLoft,
    amenities: ["WiFi", "Kitchen", "Parking", "Pet Friendly"],
  },
  {
    id: 4,
    name: "Tech Co-Work",
    location: "Hitech City, Hyderabad",
    price: 180,
    image: techcoWork,
    amenities: ["WiFi", "Tea", "Lockers", "Conference Rooms"],
  },
  {
    id: 5,
    name: "Skyline Suites",
    location: "Kondapur, Hyderabad",
    price: 230,
    image: downtownOffice,
    amenities: ["WiFi", "Coffee", "Lounge", "Meeting Room"],
  },
  {
    id: 6,
    name: "Green Studio",
    location: "Jubilee Hills, Hyderabad",
    price: 210,
    image: creativeLoft,
    amenities: ["WiFi", "Kitchen", "Ergonomic Chairs", "Pet Friendly"],
  },
  {
    id: 7,
    name: "Urban Hive",
    location: "Begumpet, Hyderabad",
    price: 190,
    image: techcoWork,
    amenities: ["WiFi", "Snacks", "Tea", "Printer"],
  },
  {
    id: 8,
    name: "Sunset Workspace",
    location: "Kukatpally, Hyderabad",
    price: 240,
    image: cozyDesk,
    amenities: ["WiFi", "Coffee", "Conference Room", "Parking"],
  },
  {
    id: 9,
    name: "Elite Work Loft",
    location: "Film Nagar, Hyderabad",
    price: 260,
    image: downtownOffice,
    amenities: ["WiFi", "Snacks", "AC", "Conference Room"],
  },
  {
    id: 10,
    name: "NextGen Workspaces",
    location: "Miyapur, Hyderabad",
    price: 200,
    image: creativeLoft,
    amenities: ["WiFi", "Parking", "Printer", "Coffee"],
  },
  {
    id: 11,
    name: "Hive Station",
    location: "Ameerpet, Hyderabad",
    price: 170,
    image: techcoWork,
    amenities: ["WiFi", "AC", "Lockers", "Tea"],
  },
  {
    id: 12,
    name: "Innovate Co-Work",
    location: "Secunderabad, Hyderabad",
    price: 210,
    image: cozyDesk,
    amenities: ["WiFi", "Coffee", "Lounge", "Kitchen"],
  },
  {
    id: 13,
    name: "Downtown Innovators Hub",
    location: "Gachibowli, Hyderabad",
    price: 230,
    image: downtownOffice,
    amenities: ["WiFi", "Conference Room", "Snacks", "Ergonomic Chairs"],
  },
  {
    id: 14,
    name: "Creative Minds Studio",
    location: "Jubilee Hills, Hyderabad",
    price: 250,
    image: creativeLoft,
    amenities: ["WiFi", "Pet Friendly", "Kitchen", "Lounge"],
  },
  {
    id: 15,
    name: "Hitech Business Bay",
    location: "Hitech City, Hyderabad",
    price: 270,
    image: techcoWork,
    amenities: ["WiFi", "Meeting Rooms", "Snacks", "Lockers"],
  },
  {
    id: 16,
    name: "WorkSmart Space",
    location: "Kondapur, Hyderabad",
    price: 220,
    image: cozyDesk,
    amenities: ["WiFi", "Tea", "Parking", "Printer"],
  },
  {
    id: 17,
    name: "Metro Co-Work",
    location: "LB Nagar, Hyderabad",
    price: 180,
    image: downtownOffice,
    amenities: ["WiFi", "Coffee", "Snacks", "Meeting Room"],
  },
  {
    id: 18,
    name: "UrbanWork Lounge",
    location: "Manikonda, Hyderabad",
    price: 200,
    image: creativeLoft,
    amenities: ["WiFi", "Pet Friendly", "Conference Room", "AC"],
  },
];
